// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task4b.Models;

namespace Task4b.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20210521130829_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task4b.Models.Weather", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("forecast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("highTemp")
                        .HasColumnType("float");

                    b.Property<double>("lowTemp")
                        .HasColumnType("float");

                    b.HasKey("City");

                    b.ToTable("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
